stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
# prepare env datasets
  before_script:
    - echo "Preparing tet data..."
  script:
  # script neCeds a list, using hypen
    - echo "Running tests...."
    - chmod +x prepare-tests.sh
    - ./prepare-tests.sh
  after_script:
    - echo "Clean up temporary files..."
    - rm -r test-data

run_lint_tests:
  stage: test
# prepare env datasets
  before_script:
    - echo "Preparing tet data..."
  script:
  # script neCeds a list, using hypen
    - echo "Running tests...."
  after_script:
    - echo "Clean up temporary files..."


build_image:
  stage: build
  script:
    - echo "Building docker image...."
    - echo "Tagging the docker image"


push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo "Logging into docker registry...."
    - echo " Push  docker image to registry..."

deploy_image:
  stage: deploy
  script: 
      - echo " deploy new docker image to dev serve"