---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:
spec:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort: 
--- 
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  type: ClusterIP
  selector:
    app:
  ports:
    - protocol: TCP
      port: 
      targetPort: 